### PR TITLE
added animation for particle's opacity

### PR DESCRIPTION
**Pull request by thechunsik**
- animating particle's opacity 
- added 2 params more: anim, anim_speed

### CODE REVIEW

**Comment by VincentGarreau** [comment]
Thank you, i added this great feature into the 1.1.0 release :+1:

**Comment by thechunsik** [comment]
finally you've come back!

**Comment by thechunsik** [comment]
it could be much better to merge other's source not to write new code by ourself. But I can understand that you've come back since last merge pull requests :) anyway, glad to see you come back :ghost: :+1:

**Comment by VincentGarreau** [comment]
Hey @thechunsik. Sorry, my mistake! I tried to merge your pull request, but i had an error. I think it's it's due to the "unknown repository":
```
thechunsik  wants to merge 4 commits into VincentGarreau:dev from unknown repository
````
Sorry for that, and many thanks for your code!

**Comment by thechunsik** [comment]
Oh, no problem! I understand this circumstance! Love your project :) Thx :+1:

**Pull request closed without merging**
