### PR TITLE
Improve merge from parameters

### PR DESCRIPTION
**Pull request by alex3165**

### CODE REVIEW

**Comment by VincentGarreau** [comment]
Wouh, smart! Thanks @alex3165, i merged into the dev branch :+1:

PS: I don't know why you're not with the contributors, GitHub don't find your profile with this PR...

screen

**Comment by alex3165** [comment]
Hello Vincent,

Hum yes I forgot to record my work email in github, I just fixed it, hope
it will work if you merge now. Anyway I'll try to add glitch effect to the
particles now :)

2015-03-04 19:54 GMT+01:00 Vincent Garreau <notifications@github.com>:

> Wouh, smart! Thanks @alex3165 <https://github.com/alex3165>, i merged
> into the dev branch [image: :+1:]
>
> PS: I don't know why you're not with the contributors, GitHub don't find
> your profile with this PR...
>
> [image: screen]
> <https://cloud.githubusercontent.com/assets/961898/6490658/31150400-c2a8-11e4-8e04-42442318c248.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VincentGarreau/particles.js/pull/45#issuecomment-77220788>
> .
>



-- 
[image: logo sensmove]Sensmove
Alexandre Rieux

Art director & Software developer

06.80.58.91.87 | 35000 Rennes

**Comment by thechunsik** [comment]
the contributors of PR on only master branch will be on the list of contributors :)

**Comment by VincentGarreau** [comment]
Right, you're in! ;)

**Pull request merged**
